"""add task_comments table and indexes

Revision ID: c4600ab7c64d
Revises: 106921c91b44
Create Date: 2025-08-18 17:47:28.973892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4600ab7c64d'
down_revision = '106921c91b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_comments_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_parent_task_id_tasks'), type_='foreignkey')
        batch_op.create_foreign_key('fk_tasks_parent', 'tasks', ['parent_task_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_parent', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tasks_parent_task_id_tasks'), 'tasks', ['parent_task_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('task_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_comments_created_at'))

    # ### end Alembic commands ###
