"""initial schema

Revision ID: cb3fec638ac2
Revises: 
Create Date: 2025-08-11 23:49:58.510184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb3fec638ac2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('clients',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('attachments',
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=400), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_owner_id'), ['owner_id'], unique=False)

    op.create_table('components',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('default_unit_price_usd', sa.Float(), nullable=True),
    sa.Column('uom', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'name', name='uq_components_category_name')
    )
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_components_category_id'), ['category_id'], unique=False)

    op.create_table('projects',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('budget_amount_usd', sa.Float(), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_code'), ['code'], unique=True)

    op.create_table('expenses',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('subtotal_usd', sa.Float(), nullable=False),
    sa.Column('tax_usd', sa.Float(), nullable=False),
    sa.Column('total_usd', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_project_id'), ['project_id'], unique=False)

    op.create_table('project_categories',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('base_cost_usd', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'category_id', name='uq_project_categories_proj_cat')
    )
    with op.batch_alter_table('project_categories', schema=None) as batch_op:
        batch_op.create_index('ix_pc_proj_cat', ['project_id', 'category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_categories_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_categories_project_id'), ['project_id'], unique=False)

    op.create_table('project_components',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price_usd', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'component_id', name='uq_project_component_unique')
    )
    with op.batch_alter_table('project_components', schema=None) as batch_op:
        batch_op.create_index('ix_proj_comp_proj_cat', ['project_id', 'category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_components_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_components_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_components_project_id'), ['project_id'], unique=False)

    op.create_table('tasks',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assignee_user_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_project_id'), ['project_id'], unique=False)

    op.create_table('expense_lines',
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('project_component_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_price_usd', sa.Float(), nullable=True),
    sa.Column('line_total_usd', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['project_component_id'], ['project_components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense_lines', schema=None) as batch_op:
        batch_op.create_index('ix_exp_line_expense_category', ['expense_id', 'category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_lines_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_lines_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_lines_expense_id'), ['expense_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_lines_project_component_id'), ['project_component_id'], unique=False)

    op.create_table('task_comments',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_comments_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_comments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_task_comments_task_id'))

    op.drop_table('task_comments')
    with op.batch_alter_table('expense_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_lines_project_component_id'))
        batch_op.drop_index(batch_op.f('ix_expense_lines_expense_id'))
        batch_op.drop_index(batch_op.f('ix_expense_lines_component_id'))
        batch_op.drop_index(batch_op.f('ix_expense_lines_category_id'))
        batch_op.drop_index('ix_exp_line_expense_category')

    op.drop_table('expense_lines')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_project_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('project_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_components_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_components_component_id'))
        batch_op.drop_index(batch_op.f('ix_project_components_category_id'))
        batch_op.drop_index('ix_proj_comp_proj_cat')

    op.drop_table('project_components')
    with op.batch_alter_table('project_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_categories_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_categories_category_id'))
        batch_op.drop_index('ix_pc_proj_cat')

    op.drop_table('project_categories')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_project_id'))

    op.drop_table('expenses')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_code'))
        batch_op.drop_index(batch_op.f('ix_projects_client_id'))

    op.drop_table('projects')
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_components_category_id'))

    op.drop_table('components')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_owner_id'))

    op.drop_table('attachments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('clients')
    op.drop_table('categories')
    # ### end Alembic commands ###
